# Generated by Django 3.0.5 on 2020-04-25 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='nome de usuario', max_length=100, null=True)),
                ('email', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.Room')),
                ('schooL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
