# Generated by Django 3.0.5 on 2020-04-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='schooL',
            new_name='school',
        ),
    ]
