# Generated by Django 3.0.5 on 2020-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20200425_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
